name: Deploy snapshot to AWS
on:
  push:
    branches:
      - "dev"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'



      - name: Build with Maven
        run: |
          cd snapshot-spring-boot
          mvn clean install -DskipTests
          JAR_PATH=$(find $PWD -name '*.jar' -type f)
          echo "jar_file=$JAR_PATH" >> $GITHUB_ENV

      # - name: Find JAR file
      #   id: find-jar
      #   run: echo "jar_file=$(find $PWD/snapshot-spring-boot -name '*.jar' -type f)" >> $GITHUB_ENV

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: snapshot
          environment_name: Snapshot-env
          version_label: snapshot_${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-eu-central-1-905418382196
          region: eu-central-1
          deployment_package: ${{ env.jar_file }}
          wait_for_deployment: true
          wait_for_environment_recovery: true
