name: Gatling tests
on:
  push:
    branches:
      - "test"

jobs:
  gatling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          cd snapshot-spring-boot
          mvn clean install -DskipTests

      - name: Start app and test
        run: |
          cd /home/runner/work/snapshot/snapshot/snapshot-spring-boot/target/
          java -jar snapshot-spring-boot-1.2.0.jar &
          APP_PID=$! 
          sleep 30s 
          cd ..
          mvn gatling:test
          kill $APP_PID
        env:
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: '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'
          MAIL_USERNAME: 'waytoenvy@gmail.com'
          MAIL_PASSWORD: 'gcjw hfyl hisl rpnm'
  
